# Generated by Django 4.1.3 on 2022-11-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_remove_worker_groups_remove_worker_position_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskType",
        ),
    ]
