# Generated by Django 4.1.3 on 2022-12-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_alter_breakdown_repair_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='breakdown_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='log.breakdowntype'),
        ),
    ]
